# Generated by Django 4.0.6 on 2022-08-02 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('progress', models.CharField(max_length=5)),
                ('comments', models.CharField(max_length=100)),
            ],
        ),
    ]
